"""French vocabulary shared by the text generators."""


# Verb lemmas mirrored from structured French vocabulary notes on 2026-07-30.
# Croire is also included from its legacy note, which predates POS metadata.
VERBES = (
    "aller",
    "alphabétiser",
    "aimer",
    "apaiser",
    "arracher",
    "avoir",
    "balloter",
    "buter",
    "cambrioler",
    "conquérir",
    "consacrer",
    "contrer",
    "copier",
    "croire",
    "domestiquer",
    "débrider",
    "décourager",
    "décélérer",
    "délivrer",
    "démissionner",
    "dénaturer",
    "effectuer",
    "empoigner",
    "enfermer",
    "envier",
    "exercer",
    "être",
    "flatter",
    "fournir",
    "frimer",
    "gagner",
    "gâcher",
    "intimider",
    "manger",
    "menacer",
    "miroiter",
    "musarder",
    "mériter",
    "parler",
    "patauger",
    "perquisitionner",
    "plonger",
    "pouvoir",
    "rallier",
    "relier",
    "remettre",
    "remédier",
    "renouer",
    "reproduire",
    "réfléchir",
    "siroter",
    "soupçonner",
    "surmonter",
    "triompher",
    "venger",
)
